language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t khalid50/mock-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khalid50/mock-docker-react npm run test